pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                // Checkout your version control repository (e.g., Git)
                checkout scm
            }
        }

        stage('TF init & validate') {
            when {
                anyOf {
                    branch "prod"
                    branch "dev"
                    changeRequest()
                }
            }
            steps {
                container('terraform') {
                    sh '''
                    if [[ $CHANGE_TARGET ]]; then
                        TARGET_ENV=$CHANGE_TARGET
                    else
                        TARGET_ENV=$BRANCH_NAME
                    fi

                    if [ -d "example-pipelines/environments/${TARGET_ENV}/" ]; then
                        cd example-pipelines/environments/${TARGET_ENV}
                        terraform init
                        terraform validate
                    else
                        for dir in example-pipelines/environments/*/
                        do 
                            cd ${dir}
                            env=${dir%*/}
                            env=${env#*/}
                            echo ""
                            echo "*************** TERRAFORM INIT and VALIDATE ******************"
                            echo "******* At environment: ${env} ********"
                            echo "*************************************************"
                            terraform init || exit 1
                            terraform validate || exit 1
                            cd ../../../
                        done
                    fi
                    '''
                }
            }
        }

        stage('TF plan') {
            when {
                anyOf {
                    branch "prod"
                    branch "dev"
                    changeRequest()
                }
            }
            steps {
                container('terraform') {
                    sh '''
                    if [[ $CHANGE_TARGET ]]; then
                        TARGET_ENV=$CHANGE_TARGET
                    else
                        TARGET_ENV=$BRANCH_NAME
                    fi

                    if [ -d "example-pipelines/environments/${TARGET_ENV}/" ]; then
                        cd example-pipelines/environments/${TARGET_ENV}
                        terraform plan
                    else
                        for dir in example-pipelines/environments/*/
                        do 
                            cd ${dir}
                            env=${dir%*/}
                            env=${env#*/}
                            echo ""
                            echo "*************** TERRAFORM PLAN ******************"
                            echo "******* At environment: ${env} ********"
                            echo "*************************************************"
                            terraform plan || exit 1
                            cd ../../../
                        done
                    fi
                    '''
                }
            }
        }

        stage('TF Apply') {
            when {
                anyOf {
                    branch "prod"
                    branch "dev"
                }
            }
            steps {
                container('terraform') {
                    sh '''
                    TARGET_ENV=$BRANCH_NAME

                    if [ -d "example-pipelines/environments/${TARGET_ENV}/" ]; then
                        cd example-pipelines/environments/${TARGET_ENV}
                        terraform apply -input=false -auto-approve
                    else
                        echo "*************** SKIPPING APPLY ******************"
                        echo "Branch '$TARGET_ENV' does not represent an official environment."
                        echo "*************************************************"
                    fi
                    '''
                }
            }
        }
    }
}
